# -*- coding: utf-8 -*-

from voluptuous import All, Length, Any

from ..validation_functions import (country_code, email_address, credit_card_number,
                                    expiration_date, accepted_payment_type, ip_address,
                                    bool_to_one_or_zero, bool_to_yes_or_no, decimal)

condition_for = {'first_name': All(str, Length(max=64)),
                 'last_name': All(str, Length(max=64)),
                 'address1': All(str, Length(max=64)),
                 'address2': All(str, Length(max=64)),
                 'city': All(str, Length(max=32)),
                 'state': All(str, Length(max=32)),
                 'zip': All(str, Length(max=10)),
                 'country': All(str, country_code, Length(2)),
                 'phone': All(Any(str, int), lambda phone: str(phone), Length(max=18)),  # FIXME
                 'email': All(str, email_address, Length(max=96)),
                 'credit_card_type': All(str, accepted_payment_type),
                 'credit_card_number': All(str, credit_card_number,
                                           Length(max=20)),
                 'expiration_date': All(expiration_date, Length(4)),
                 'cvv': All(str, Length(min=3, max=4)),
                 'tran_type': 'Sale',
                 'ip_address': All(str, ip_address, Length(max=15)),
                 'AFID': All(str, Length(max=255)),
                 'SID': All(str, Length(max=255)),
                 'AFFID': All(str, Length(max=255)),
                 'C1': All(str, Length(max=255)),
                 'C2': All(str, Length(max=255)),
                 'C3': All(str, Length(max=255)),
                 'AID': All(str, Length(max=255)),
                 'OPT': All(str, Length(max=255)),
                 'click_id': All(str, Length(max=255)),
                 'product_id': int,
                 'campaign_id': int,
                 'shipping_id': int,
                 'upsell_count': All(bool, bool_to_one_or_zero),
                 'upsell_product_ids': [int],
                 'billing_same_as_shipping': All(bool, bool_to_yes_or_no),
                 'notes': All(str, Length(max=512)),
                 'preserve_force_gateway': All(bool, bool_to_one_or_zero),
                 'created_by': All(str, Length(max=100)),
                 'thm_session_id': All(str, Length(max=255)),
                 'total_installments': int,
                 'alt_pay_token': All(str, Length(max=20)),
                 'alt_pay_payer_id': All(str, Length(max=20)),
                 'secret_ssn': All(int, Length(max=4)),
                 'force_subscription_cycle': bool,
                 'recurring_days': int,
                 'subscription_week': Any(1, 2, 3, 4, 5),
                 'subscription_day': Any(1, 2, 3, 4, 5, 6, 7),
                 'master_order_id': int,
                 'promo_code': All(str, Length(max=100)),
                 'temp_customer_id': All(str, Length(max=32)),
                 # authorize_payment
                 'auth_amount': decimal,
                 'cascade_enabled': All(bool, bool_to_one_or_zero),
                 'save_customer': All(bool, bool_to_one_or_zero),
                 # NewOrderWithProspect
                 'prospect_id': int,
                 # three_d_redirect
                 'order_id': int, }

# Duplicate conditions
condition_for.update({'shipping_address1': condition_for['address1'],
                      'shipping_address2': condition_for['address2'],
                      'shipping_city': condition_for['city'],
                      'shipping_state': condition_for['state'],
                      'shipping_zip': condition_for['zip'],
                      'shipping_country': condition_for['country'],
                      'billing_first_name': condition_for['first_name'],
                      'billing_last_name': condition_for['last_name'],
                      'billing_address1': condition_for['address1'],
                      'billing_address2': condition_for['address2'],
                      'billing_city': condition_for['city'],
                      'billing_state': condition_for['state'],
                      'billing_zip': condition_for['zip'],
                      'billing_country': condition_for['country'], })