# -*- coding: utf-8 -*-

from voluptuous import Required, Optional, Length, All, Any

from ..method import TransactionMethod
from ..validation_functions import (valid_country_code, email_address, accepted_payment_type,
                                    datetime, valid_credit_card_number, valid_ip_address)


class NewOrderWithProspect(TransactionMethod):
    schema = {Optional('first_name'): All(str, Length(max=64)),
              Optional('last_name'): All(str, Length(max=64)),
              Optional('shipping_address1'): All(str, Length(max=64)),
              Optional('shipping_address2'): All(str, Length(max=64)),
              Optional('shipping_city'): All(str, Length(max=32)),
              Optional('shipping_state'): All(str, Length(max=32)),
              Optional('shipping_zip'): All(int, Length(max=10)),
              Optional('shipping_country'): All(str, valid_country_code, Length(2)),
              Optional('billing_first_name'): All(str, Length(min=1, max=64)),
              Optional('billing_last_name'): All(str, Length(min=1, max=64)),
              Optional('billing_address1'): All(str, Length(min=1, max=64)),
              Optional('billing_address2'): All(str, Length(min=1, max=64)),
              Optional('billing_city'): All(str, Length(max=32)),
              Optional('billing_state'): All(str, Length(max=32)),
              Optional('billing_zip'): All(int, Length(max=10)),
              Optional('billing_country'): All(str, valid_country_code, Length(2)),
              Optional('phone'): All(int, Length(max=18)),
              Optional('email'): All(str, email_address, Length(max=96)),
              Required('credit_card_type'): All(str, accepted_payment_type),
              Required('credit_card_number'): All(str, valid_credit_card_number,
                                                  Length(max=20)),
              Required('expiration_date'): datetime,
              Required('cvv'): All(int, Length(min=3, max=4)),
              Required('tran_type'): 'Sale',
              Optional('ip_address'): All(str, valid_ip_address, Length(max=15)),
              Optional('AFID'): All(str, Length(max=255)),
              Optional('SID'): All(str, Length(max=255)),
              Optional('AFFID'): All(str, Length(max=255)),
              Optional('C1'): All(str, Length(max=255)),
              Optional('C2'): All(str, Length(max=255)),
              Optional('C3'): All(str, Length(max=255)),
              Optional('AID'): All(str, Length(max=255)),
              Optional('OPT'): All(str, Length(max=255)),
              Optional('click_id'): All(str, Length(max=255)),
              Required('product_id'): int,
              Required('campaign_id'): int,
              Required('shipping_id'): int,
              Required('upsell_count'): bool,
              Optional('upsell_product_ids'): [int],
              Required('prospect_id'): int,
              Optional('billing_same_as_shipping'): bool,
              Optional('notes'): All(str, Length(max=512)),
              Optional('preserve_force_gateway'): bool,
              Optional('created_by'): All(str, Length(max=100)),
              Optional('thm_session_id'): All(str, Length(max=255)),
              Optional('total_installments'): int,
              Optional('alt_pay_token'): All(str, Length(max=20)),
              Optional('alt_pay_payer_id'): All(str, Length(max=20)),
              Optional('secret_ssn'): All(int, Length(max=4)),
              Optional('force_subscription_cycle'): bool,
              Optional('recurring_days'): int,
              Optional('subscription_week'): Any(1, 2, 3, 4, 5),
              Optional('subscription_day'): Any(1, 2, 3, 4, 5, 6, 7),
              Optional('master_order_id'): int,
              Optional('promo_code'): All(str, Length(max=100)),
              Optional('temp_customer_id'): All(str, Length(max=32)), }